name: CD Pipeline

trigger: none

resources:
  pipelines:
  - pipeline: ci-pipeline
    source: 'CI Pipeline'
    trigger:
      branches:
        include:
          - main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, from the CD pipeline!
  displayName: 'Run a one-line script'