name: CD-Pipeline

trigger: none

resources:
  pipelines:
  - pipeline: dependant-cd-pipeline
    source: john-morsley.azure-pipelines-poc-ci
    project: azure-pipeline-poc
    branch: main
    trigger:
     branches:
      include:
      - main 

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: 'morsley-uk-test'
  appName: 'morsley-uk-test-api'
  artifactName: 'drop'
  packagePath: 'Morsley.UK.Test.API.zip'

steps:
# Download artifacts from CI pipeline...
- task: DownloadPipelineArtifact@2
  displayName: "--> Download CI Pipeline Artifacts <--"
  inputs:
    buildType: 'specific'
    project: 'azure-pipeline-poc'
    definition: 'john-morsley.azure-pipelines-poc-ci'
    buildVersionToDownload: 'latest'
    artifactName: 'drop'
    targetPath: '$(Pipeline.Workspace)/artifacts'

# Show downloaded artifacts...
- task: CmdLine@2
  displayName: "--> Show downloaded artifacts <--"
  inputs:
    script: |
      echo "Contents of artifacts directory:"
      ls -la $(Pipeline.Workspace)/artifacts
      echo "Contents of API directory:"
      ls -la $(Pipeline.Workspace)/artifacts/api

# Deploy our test API to production...  
#- task: AzureWebApp@1
#  displayName: '--> Deploy to Production <--'
#  inputs: 
#    azureSubscription: '$(azureSubscription)'
#    appName: '$(appName)'
#    appType: 'webApp'
#    package: '$(Pipeline.Workspace)/artifacts/api'
