name: CD-Pipeline

trigger: none

resources:
  pipelines:
  - pipeline: dependant-cd-pipeline
    source: john-morsley.azure-pipelines-poc-ci
    project: azure-pipeline-poc
    branch: main
    trigger:
     branches:
      include:
      - main 

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, from the CD pipeline!
  displayName: 'Run a one-line script'