name: CD-Pipeline

trigger: none

resources:
  pipelines:
  - pipeline: dependant-cd-pipeline
    project: azure-pipeline-poc
    source: john-morsley.azure-pipelines-poc-ci

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, from the CD pipeline!
  displayName: 'Run a one-line script'